# Generated by Django 2.1.7 on 2019-03-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default=None, max_length=1)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('hindu', 'Hindu'), ('budha', 'Budha'), ('lain', 'Lain-lain')], default=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
                ('nama_ibu', models.CharField(max_length=50)),
            ],
        ),
    ]
